/************************************************************************
 * Dynamic Dollar Shop - MAIN INCLUDE :: ENV User Information (Sourcemod)
 * 
 * Copyright (C) 2012-2015 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
 ***********************************************************************/
#define DDS_ENV_ITEM_MAX						300
#define DDS_ENV_ITEMCG_MAX						20
#define DDS_ENV_USEENV_MAX						50

#define DDS_ENV_VAR_GLONAME_SIZE				300
#define DDS_ENV_VAR_ENV_SIZE					512
#define DDS_ENV_VAR_SUPPORT_GAME_NUM			5