/************************************************************************
 * Dynamic Dollar Shop - MAIN INCLUDE :: ENV Core Information (Sourcemod)
 * 
 * Copyright (C) 2012-2015 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
 ***********************************************************************/
#define DDS_ENV_CORE_NAME						"Dynamic Dollar Shop"
#define DDS_ENV_CORE_AUTHOR						"Eakgnarok"
#define DDS_ENV_CORE_VERSION					"2.0.0a"
#define DDS_ENV_CORE_HOMEPAGE					"http://sourcemod.net"

#define DDS_ENV_CORE_CHAT_GLOPREFIX				"[DDS]"