/************************************************************************
 * User Class Management - MAIN INCLUDE :: ENV Core Information (Sourcemod)
 * 
 * Copyright (C) 2015 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
 ***********************************************************************/
 #define UCM_ENV_CORE_NAME							"User Class Management"
 #define UCM_ENV_CORE_AUTHOR						"Eakgnarok"
 #define UCM_ENV_CORE_VERSION						"1.0.0"
 #define UCM_ENV_CORE_HOMEPAGE						"http://sourcemod.net"

 #define UCM_ENV_CORE_CHAT_GLOPREFIX				"[UCM]"