/************************************************************************
 * User Class Management - MAIN INCLUDE :: ENV User Information (Sourcemod)
 * 
 * Copyright (C) 2015 Eakgnarok
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
 ***********************************************************************/
#define UCM_ENV_CLASS_MAX						10

#define UCM_ENV_VAR_GLONAME_SIZE				256
#define UCM_ENV_VAR_ENV_SIZE					512
#define UCM_ENV_USEENV_MAX						50